### PR TITLE
Guard against nil covers in helm-emms-dired-transformer

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Sorry but I don't understand this usage of guard.
With the actual code `c` should be returned only if pedicate returns non
nil. To my understanding of pcase (guard c) does nothing more than (and c).

Pierre Neidhardt <notifications@github.com> writes:

> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/emacs-helm/helm-emms/pull/15
>
> Commit Summary
>
>   * Guard against nil covers in helm-emms-dired-transformer
>
> File Changes
>
>   * M helm-emms.el (2)
>
> Patch Links:
>
>   * https://github.com/emacs-helm/helm-emms/pull/15.patch
>   * https://github.com/emacs-helm/helm-emms/pull/15.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
This confused me too at first, but the `and` of pcase does not test "c", it only
binds it.

To convince yourself of my claim, try the following:

```elisp
(pcase nil
  ((and c)
   (message "%s" c)))
```

**Comment by thierryvolpiatto** [comment]
Yes you are right, it's confusing indeed, so I would write it like this to be more lispy and make the code less confusing when we read it later (I am sure I will forget what this guard is for in one month or maybe less):

```elisp
(pcase (emms-browser-get-cover-from-path d 'small)
  ((and c (guard (and c (file-exists-p c))) c))
  (_ (car emms-browser-default-covers)))
```
So yes `and` is just a kind of let-binding but don't test at all.

**Comment by Ambrevar** [comment]
Yes, I think it's wiser to make this explicit :)

**Comment by Ambrevar** [comment]
@thierryvolpiatto : Updated!

**Comment by thierryvolpiatto** [comment]
Thanks!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> @thierryvolpiatto : Updated!

Fixed a small paren error (the snippet of code I sent was fully not tested
and wrong).

Thanks.

-- 
Thierry

**Pull request merged**
