### PR TITLE
Offer optimized function to walk directories.

### PR DESCRIPTION
**Pull request by Ambrevar**
* helm-emms.el (helm-emms-find-program): New user var.
(helm-emms-walk-directory-with-find): New function.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
I am not sure `helm-emms-walk-directory-with-find` docstring is correct:

"Like `helm-emms-walk-directory-with-find'"
vs
"Like `helm-emms-walk-directory'"

Pierre Neidhardt <notifications@github.com> writes:

>   * helm-emms.el (helm-emms-find-program): New user var.
>     (helm-emms-walk-directory-with-find): New function.
>
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/emacs-helm/helm-emms/pull/13
>
> Commit Summary
>
>   * Offer optimized function to walk directories.
>
> File Changes
>
>   * M helm-emms.el (16)
>
> Patch Links:
>
>   * https://github.com/emacs-helm/helm-emms/pull/13.patch
>   * https://github.com/emacs-helm/helm-emms/pull/13.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Oops!  Fixed!

**Comment by thierryvolpiatto** [comment]
Ok merged, thanks.

**Comment by Ambrevar** [comment]
Thanks!

**Pull request merged**
